import { Router } from 'express';
import { authRouter } from './auth/auth.routes';
import { usersRouter } from './users/users.routes';
import { editionsRouter } from './editions/editions.routes';
import { categoriesRouter } from './categories/categories.routes';
import { competitionsRouter } from './competitions/competitions.routes';
import { groupsRouter } from './groups/groups.routes';
import { teamsRouter } from './teams/teams.routes';
import { playersRouter } from './players/players.routes';
import { rostersRouter } from './rosters/rosters.routes';
import { matchesRouter } from './matches/matches.routes';
import { matchEventsRouter } from './match-events/match-events.routes';
import { standingsRouter } from './standings/standings.routes';
import { statsRouter } from './stats/stats.routes';
import { transfersRouter } from './transfers/transfers.routes';
import { adsRouter } from './ads/ads.routes';
import { uploadsRouter } from './uploads/uploads.routes';
import { dashboardRouter } from './dashboard/dashboard.routes';
import { publicRouter } from './public/public.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/editions', editionsRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/competitions', competitionsRouter);
apiRouter.use('/teams', teamsRouter);
apiRouter.use('/players', playersRouter);
apiRouter.use('/matches', matchesRouter);
apiRouter.use('/standings', standingsRouter);
apiRouter.use('/stats', statsRouter);
apiRouter.use('/transfers', transfersRouter);
apiRouter.use('/ads', adsRouter);
apiRouter.use('/uploads', uploadsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/public', publicRouter);
apiRouter.use('/', groupsRouter);
apiRouter.use('/', rostersRouter);
apiRouter.use('/', matchEventsRouter);
