export const ROUTES = {
  login: '/login',
  admin: {
    dashboard: '/admin',
    editions: '/admin/ediciones',
    editionDetail: '/admin/ediciones/:id',
    categories: '/admin/categorias',
    competitions: '/admin/competiciones',
    competitionDetail: '/admin/competiciones/:id',
    teams: '/admin/equipos',
    teamDetail: '/admin/equipos/:id',
    players: '/admin/jugadores',
    playerDetail: '/admin/jugadores/:id',
    schedule: '/admin/programacion',
    matchDetail: '/admin/partidos/:id',
    stats: '/admin/estadisticas',
    ads: '/admin/publicidad',
    audit: '/admin/auditoria',
  },
  team: {
    home: '/equipo',
    squads: '/equipo/plantillas',
    stats: '/equipo/estadisticas',
    history: '/equipo/historial',
    transfers: '/equipo/traspasos',
  },
  public: {
    home: '/',
    competitions: '/competiciones',
    stats: '/estadisticas',
    teams: '/equipos',
    schedule: '/calendario',
    live: '/en-vivo',
    history: '/historico',
  },
} as const;
